#dependencies
markdown:         redcarpet
highlighter:      pygments

#settings
permalink:        /post/:title/
paginate:         10
paginate_path:    page/:num
encoding:         utf-8
ga_id:            UA-54538344-1

#params
title:            Евгений Абросимов
tagline:          Keep calm and 'use strict';
description:      Здесь будет описание
keywords:         Здесь будет список ключевых слов
url:              http://sadcitizen.github.io
version:          0.3.0
comments:         true
social:           true
ga:               true
metrika:          true

#author
author:
  name:           Евгений Абросимов
  email:          iam@instanceof.pro

links:
  github:         http://github.com/sadcitizen
  twitter:        http://twitter.com/abrosimov
  linkedin:       http://linkedin.com/profile/view?id=246916719
  rss:            /atom.xml
  about:          /about/

#public
public:
  images:         /public/images
  styles:         /public/css
  scripts:        /public/js
