#dependencies
markdown:         redcarpet
highlighter:      pygments

#settings
permalink:        /post/:title/
paginate:         10
paginate_path:    page/:num
encoding:         utf-8

#params
title:            'Евгений Абросимов'
tagline:          Keep calm and 'use strict';
description:      ''
keywords:         ''
url:              http://instanceofpro.github.io

version:          0.2.0

#author
author:
  name:           'Евгений Абросимов'
  email:          iam@instanceof.pro

links:
  github:         http://github.com/instanceofpro
  twitter:        http://twitter.com/instanceofpro
  linkedin:       http://linkedin.com/profile/view?id=246916719
  rss:            /atom.xml
  about:          /about.html

#public
public:
  images:         '/public/images'
  styles:         '/public/css'
