#dependencies
markdown:         redcarpet
highlighter:      pygments

#settings
permalink:        /post/:title/
paginate:         10
paginate_path:    page/:num
encoding:         utf-8

#params
title:            Блог Евгения Абросимова
tagline:          Keep calm and 'use strict';
description:      Здесь будет описание
keywords:         Здесь будет список ключевых слов
url:              http://instanceof.pro
comments:         true
social:           true
version:          0.2.0

#author
author:
  name:           Евгений Абросимов
  email:          iam@instanceof.pro

links:
  github:         http://github.com/instanceofpro
  twitter:        http://twitter.com/instanceofpro
  linkedin:       http://linkedin.com/profile/view?id=246916719
  rss:            /atom.xml
  about:          /about/

#public
public:
  images:         /public/images
  styles:         /public/css
  scripts:        /public/js
